version: '3.1'

services:
  postgres:
    build:
      context: .
      dockerfile: ../postgres/Dockerfile
    volumes:
      - ../postgres/pgdata:/pgdata
    ports:
      - "5420:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
